### ISSUE TITLE
"Content Security Policy" errors in Nextcloud for calls to Matoma

### ISSUE THREAD

**Issue by brtptrs** [sualko/cloud_piwik#80]
Recently we are seeing "Content Security Policy" errors in Nextcloud for calls to Matomo.  It seems the errors only occur  in some Versions of Firefox and on with cloud_piwik on Nextcloud. Additionally not all calls to Matomo is blocked.

We have Matomo integrated in numerous different systems and the error is only shown in Nextcloud.

Nectcloud 20.0.2
Firefox 83
cloud_piwik 0.7.0

A few things changed at about the time the errors started showing up:
Nextcloud upgrade from 19.x to 20.0.2
New Firefox version 83
Matomo upgrade from 3.x to 4..0.5

This makes it difficult to pin down, but since none of our other installations are showing errors it must somehow be related to the NC + cloud_piwik combination.

**Comment by sualko** [comment]
If I remember correctly NC is using different CSP approaches depending on the browser. So maybe something changed there. I don't have time to track this down (especially without any error message), therefore I recommend to setup a rewrite/proxy.

**Comment by GuiGuiSoft** [comment]
Hello,

I have the same issue since I updated Matomo 4+, [changelog says](https://fr.matomo.org/changelog/matomo-4-0-0/) :  

> The JS tracker is now tracking using « navigator.sendBeacon » by default. If you are using a Content Security Policy header, please adjust your header to also allow « connect-src » see the [example in our FAQ](https://fr.matomo.org/faq/general/faq_20904/). Alternatively, you can disable « sendBeacon » using the JS tracker method `_paq.push(["disableAlwaysUseSendBeacon"]);`.

Error in the console is :  
![image](https://user-images.githubusercontent.com/8069239/105731192-72db2c00-5f2f-11eb-8c83-a11c5efdee22.png)


The CSP seems generated by NextCloud itself.  
If defined in the webserver conf we can not define the script-src value. Example :  
![image](https://user-images.githubusercontent.com/8069239/105730777-02340f80-5f2f-11eb-9164-b484a989e782.png)


I hope it can help.
Regards.

**Comment by sualko** [comment]
@GuiGuiSoft sounds like you have found the reason for this error message. Thanks a lot. Can you try to add `$policy->addAllowedConnectDomain($allowedUrl);` to https://github.com/sualko/cloud_piwik/blob/d52a2be9f355fc759af1d9e4b57c72b1d981e71f/appinfo/app.php#L29-L31

**Comment by brtptrs** [comment]
I think this fixed it. 
I don't see the error any more, and matomo is showing the hits again.
Thank you.

**Comment by sualko** [comment]
fixed in ae05ca1b3f192756e94331e0846d377df50e50f1
